import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";

import { PageHero } from "@/components/sections/PageHero";
import { CTABand } from "@/components/sections/CTABand";
import { ClinicalReview } from "@/components/sections/ClinicalReview";
import { Accordion } from "@/components/ui/Accordion";
import { ButtonLink, ArrowLink } from "@/components/ui/Button";
import { ServiceIcon } from "@/components/ui/ServiceIcon";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { MaskText, Reveal, Stagger, StaggerItem } from "@/components/motion";
import { ParallaxImage } from "@/components/motion/ParallaxImage";
import { services, getService, servicePath } from "@/lib/services";
import { leadDoctors } from "@/lib/doctors";
import { SITE_URL, site } from "@/lib/site";
import {
  breadcrumbSchema,
  faqSchema,
  graph,
  medicalWebPageSchema,
  physicianSchema,
  serviceSchema,
} from "@/lib/schema";

const cosmeticHubSlugs = new Set<string>([
  "smile-makeover",
  "dental-veneers",
  "teeth-whitening",
  "invisalign-clear-aligners",
  "dental-crowns-bridges",
]);

export function generateStaticParams() {
  return services.map((s) => ({ slug: s.slug }));
}

export async function generateMetadata(
  props: PageProps<"/services/[slug]">,
): Promise<Metadata> {
  const { slug } = await props.params;
  const service = getService(slug);
  if (!service) return {};

  return {
    title: service.metaTitle,
    description: service.metaDescription,
    alternates: { canonical: `/services/${service.slug}` },
    openGraph: {
      title: service.metaTitle,
      description: service.metaDescription,
      url: `/services/${service.slug}`,
      type: "article",
      // No explicit `images` — an inline value here would override the
      // branded card generated by opengraph-image.tsx in this folder.
    },
  };
}

export default async function ServicePage(props: PageProps<"/services/[slug]">) {
  const { slug } = await props.params;
  const service = getService(slug);
  if (!service) notFound();

  const doctors = leadDoctors(service.lead);
  const linksToCosmeticHub = cosmeticHubSlugs.has(service.slug);
  const related = service.related
    .map((s) => getService(s))
    .filter((s): s is NonNullable<typeof s> => Boolean(s));

  const trail = [
    { name: "Home", url: "/" },
    { name: "Treatments", url: "/services" },
    { name: service.name, url: `/services/${service.slug}` },
  ];

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(
            graph(
              serviceSchema(service),
              medicalWebPageSchema({
                url: `/services/${service.slug}`,
                name: service.metaTitle,
                description: service.metaDescription,
                reviewer: doctors[0],
                aboutId: `${SITE_URL}/services/${service.slug}#procedure`,
                image: service.image,
              }),
              ...doctors.map((doctor) => physicianSchema(doctor)),
              faqSchema(service.faqs),
              breadcrumbSchema(trail),
            ),
          ),
        }}
      />

      <PageHero
        eyebrow={`${service.category} · Prayagraj`}
        title={[service.heading]}
        lede={service.summary}
        trail={trail}
      >
        {/* Quick-facts rail. Two up from the smallest screen — these are short
            label/value pairs and stacking four full-width wasted a screen. */}
        <Stagger className="mt-10 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-line bg-line sm:mt-14 lg:grid-cols-4">
          {service.facts.map((f) => (
            <StaggerItem key={f.label}>
              <div className="h-full bg-surface p-4 sm:p-6">
                <p className="eyebrow text-faint">{f.label}</p>
                <p className="mt-2 font-display text-base leading-snug text-cocoa sm:mt-2.5 sm:text-xl">
                  {f.value}
                </p>
              </div>
            </StaggerItem>
          ))}
        </Stagger>
      </PageHero>

      {/* Overview + image */}
      <section className="section bg-ivory pt-0 md:pt-0">
        <div className="shell grid gap-12 lg:grid-cols-12 lg:gap-16">
          <div className="lg:col-span-7">
            <Reveal>
              <span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-tint text-terracotta">
                <ServiceIcon name={service.icon} className="h-7 w-7" />
              </span>
            </Reveal>

            <div className="prose-edc mt-8">
              {service.overview.map((p, i) => (
                <Reveal key={i} delay={i * 0.06}>
                  <p>{p}</p>
                </Reveal>
              ))}
            </div>

            <Reveal>
              <ClinicalReview doctor={doctors[0]} />
            </Reveal>

            {/* Benefits */}
            <Reveal>
              <h2 className="display-md mt-14 text-cocoa">Why it is worth doing</h2>
            </Reveal>
            <Stagger className="mt-7 grid gap-3 sm:grid-cols-2">
              {service.benefits.map((b) => (
                <StaggerItem key={b}>
                  <div className="flex h-full gap-3 rounded-xl border border-line bg-surface p-4">
                    <svg
                      viewBox="0 0 20 20"
                      className="mt-0.5 h-4 w-4 shrink-0 text-terracotta"
                      fill="none"
                      aria-hidden
                    >
                      <path
                        d="m4 10.5 4 4 8-9"
                        stroke="currentColor"
                        strokeWidth="1.8"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                    <span className="text-sm leading-relaxed text-cocoa">{b}</span>
                  </div>
                </StaggerItem>
              ))}
            </Stagger>
          </div>

          {/* Sticky sidebar */}
          <aside className="lg:col-span-5">
            <div className="lg:sticky lg:top-28">
              <ParallaxImage
                src={service.image}
                alt={service.imageAlt}
                sizes="(max-width: 1024px) 92vw, 40vw"
                strength={0.07}
                className="aspect-[4/5] rounded-2xl"
              />

              {/* Treating doctor */}
              <div className="mt-6 rounded-2xl border border-line bg-surface p-6">
                <p className="eyebrow text-brick">
                  {doctors.length > 1 ? "Treated by" : "Your specialist"}
                </p>
                <div className="mt-4 space-y-4">
                  {doctors.map((d) => (
                    <Link
                      key={d.slug}
                      href={`/doctors/${d.slug}`}
                      className="group flex items-center gap-4"
                    >
                      <span className="relative h-14 w-14 shrink-0 overflow-hidden rounded-full bg-sunk">
                        <Image
                          src={d.image}
                          alt={d.imageAlt}
                          fill
                          sizes="56px"
                          className="object-cover object-top"
                        />
                      </span>
                      <span>
                        <span className="block font-semibold text-cocoa group-hover:text-brick">
                          {d.name}
                        </span>
                        <span className="block text-xs text-muted">{d.role}</span>
                      </span>
                    </Link>
                  ))}
                </div>

                <div className="mt-6 border-t border-line pt-5">
                  <ButtonLink href="/contact" size="md" className="w-full">
                    Book a consultation
                  </ButtonLink>
                  <p className="mt-3 text-center text-xs text-muted">
                    Or call{" "}
                    <a href={`tel:${site.phone}`} className="font-semibold text-brick">
                      {site.phoneDisplay}
                    </a>
                  </p>
                </div>
              </div>

              <div className="mt-4 rounded-2xl border border-line bg-sandwash p-6">
                <p className="eyebrow text-brick">Prayagraj clinic</p>
                <h2 className="mt-3 font-display text-xl leading-tight text-cocoa">
                  Treatment at our Civil Lines clinic
                </h2>
                <p className="mt-3 text-sm leading-relaxed text-muted">
                  {site.address.street}, near {site.address.landmark},{" "}
                  {site.address.locality}, {site.address.city} ({site.address.alternateCityName}).
                </p>
                <div className="mt-4 flex flex-wrap gap-x-5 gap-y-2">
                  <Link
                    href="/locations/civil-lines-prayagraj"
                    className="text-sm font-semibold text-brick transition-colors hover:text-brick-hover"
                  >
                    Clinic & directions →
                  </Link>
                  <Link
                    href="/areas-we-serve"
                    className="text-sm font-semibold text-brick transition-colors hover:text-brick-hover"
                  >
                    Areas we serve →
                  </Link>
                  {linksToCosmeticHub && (
                    <Link
                      href="/cosmetic-dentist-prayagraj"
                      className="text-sm font-semibold text-brick transition-colors hover:text-brick-hover"
                    >
                      Cosmetic dentistry →
                    </Link>
                  )}
                </div>
              </div>
            </div>
          </aside>
        </div>
      </section>

      {/* Signs — high search-intent block */}
      <section className="section bg-sunk">
        <div className="shell grid gap-12 lg:grid-cols-12 lg:gap-16">
          <div className="lg:col-span-5">
            <SectionHeading
              eyebrow="Do you need this?"
              title={["Signs it may be", "time to come in."]}
              lede="If any of these sound familiar, it is worth a consultation — even just to be told it is nothing."
            />

            {/* A real photograph from the clinic, so the page is not carried
                entirely by stock imagery. */}
            <Reveal delay={0.15}>
              <figure className="mt-10">
                <ParallaxImage
                  src={service.clinicImage}
                  alt={service.clinicImageAlt}
                  sizes="(max-width: 1024px) 92vw, 38vw"
                  strength={0.06}
                  className="aspect-[4/3] rounded-2xl"
                />
                <figcaption className="mt-3 text-xs text-muted">
                  Real clinic photography from{" "}
                  <Link
                    href="/locations/civil-lines-prayagraj"
                    className="font-medium text-brick hover:text-brick-hover"
                  >
                    Eclectic Dental Care in Civil Lines, Prayagraj
                  </Link>
                  .
                </figcaption>
              </figure>
            </Reveal>
          </div>
          <div className="lg:col-span-7">
            <Stagger className="grid gap-3">
              {service.signs.map((s, i) => (
                <StaggerItem key={s}>
                  <div className="flex items-start gap-4 rounded-xl border border-line-strong/40 bg-ivory p-5">
                    <span className="font-display text-sm leading-6 text-terracotta lining-nums tabular-nums">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <span className="leading-relaxed text-cocoa">{s}</span>
                  </div>
                </StaggerItem>
              ))}
            </Stagger>
          </div>
        </div>
      </section>

      {/* Process */}
      <section className="section bg-ivory">
        <div className="shell">
          <SectionHeading
            eyebrow="The process"
            title={["What actually", "happens, step by step."]}
            lede="No stage of your treatment should be a surprise. This is the sequence from first appointment to finish."
          />

          <div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-line bg-line md:grid-cols-2 lg:grid-cols-3">
            {service.process.map((step, i) => (
              <Reveal key={step.title} delay={(i % 3) * 0.08}>
                <div className="group h-full bg-surface p-7 transition-colors duration-500 hover:bg-tint lg:p-8">
                  <p className="font-display text-4xl leading-none text-terracotta lining-nums tabular-nums">
                    {String(i + 1).padStart(2, "0")}
                  </p>
                  <h3 className="mt-5 font-display text-2xl leading-tight text-cocoa">
                    {step.title}
                  </h3>
                  <p className="mt-3 text-sm leading-relaxed text-muted">{step.body}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* Cost. We do not publish figures — a quoted number that changes after
          an examination helps nobody — but naming what actually moves the
          price answers the question instead of dodging it. */}
      <section className="section bg-sunk">
        <div className="shell grid gap-10 lg:grid-cols-12 lg:gap-16">
          <div className="lg:col-span-5">
            <SectionHeading
              eyebrow="Cost"
              title={["What affects", "the price."]}
              lede="We give you the full fee for your plan in writing before treatment starts, and nothing is added partway through."
            />
          </div>

          <div className="lg:col-span-7">
            <Stagger className="grid gap-3">
              {service.costFactors.map((factor, i) => (
                <StaggerItem key={factor}>
                  <div className="flex items-start gap-4 rounded-xl border border-line bg-ivory p-5">
                    <span className="font-display text-sm leading-6 text-terracotta lining-nums tabular-nums">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <span className="leading-relaxed text-cocoa">{factor}</span>
                  </div>
                </StaggerItem>
              ))}
            </Stagger>

            <Reveal delay={0.15}>
              <div className="mt-6 rounded-2xl border border-line bg-tint p-6">
                <p className="leading-relaxed text-cocoa">
                  The only honest way to price {service.name.toLowerCase()} is to
                  look at your mouth first. Book an examination and you will
                  leave knowing exactly what it costs — with no obligation to
                  start on the day.
                </p>
                <div className="mt-5 flex flex-wrap gap-3">
                  <ButtonLink href="/contact" size="md">
                    Get a written quote
                  </ButtonLink>
                  <ButtonLink href={`tel:${site.phone}`} external variant="outline" size="md">
                    Ask on the phone
                  </ButtonLink>
                </div>
              </div>
            </Reveal>
          </div>
        </div>
      </section>

      {/* Honest comparison — most treatments have a real alternative the
          patient is weighing up, and saying so plainly builds trust. */}
      {service.comparison && (
        <section className="section bg-ivory">
          <div className="shell">
            <div>
              <SectionHeading
                eyebrow="Honest comparison"
                title={[service.comparison.title]}
                lede={service.comparison.intro}
              />

              <Reveal delay={0.1}>
                <div className="mt-12 overflow-x-auto">
                  <table className="w-full min-w-[36rem] border-collapse text-left">
                    <caption className="sr-only">
                      {service.comparison.optionA} compared with{" "}
                      {service.comparison.optionB}
                    </caption>
                    <thead>
                      <tr className="border-b border-line-strong">
                        <th scope="col" className="eyebrow py-4 pr-4 text-faint">
                          &nbsp;
                        </th>
                        <th scope="col" className="py-4 pr-4">
                          <span className="font-display text-xl text-terracotta">
                            {service.comparison.optionA}
                          </span>
                        </th>
                        <th scope="col" className="py-4">
                          <span className="font-display text-xl text-cocoa">
                            {service.comparison.optionB}
                          </span>
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {service.comparison.rows.map((row) => (
                        <tr key={row.feature} className="border-b border-line">
                          <th
                            scope="row"
                            className="py-4 pr-4 align-top text-sm font-semibold text-cocoa"
                          >
                            {row.feature}
                          </th>
                          <td className="py-4 pr-4 align-top text-sm leading-relaxed text-muted">
                            {row.a}
                          </td>
                          <td className="py-4 align-top text-sm leading-relaxed text-muted">
                            {row.b}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </Reveal>

              <Reveal delay={0.15}>
                <div className="mt-10 rounded-2xl border border-line bg-surface p-7">
                  <p className="leading-relaxed text-cocoa">
                    <strong className="font-semibold">The honest version:</strong>{" "}
                    {service.comparison.verdict}
                  </p>
                </div>
              </Reveal>
            </div>
          </div>
        </section>
      )}

      {/* FAQs */}
      <section className="section bg-sandwash">
        <div className="shell grid gap-12 lg:grid-cols-12 lg:gap-16">
          <div className="lg:col-span-5">
            <SectionHeading
              eyebrow="Questions"
              title={[`${service.name}`, "— your questions."]}
              lede="The things patients at our Civil Lines clinic in Prayagraj most often ask us about this treatment."
            />
          </div>
          <div className="lg:col-span-7">
            <Accordion items={service.faqs} />
          </div>
        </div>
      </section>

      {/* Related */}
      {related.length > 0 && (
        <section className="section bg-ivory">
          <div className="shell">
            <div className="flex flex-wrap items-end justify-between gap-6">
              <h2 className="display-md text-cocoa">
                <MaskText lines={["Related treatments"]} />
              </h2>
              <ArrowLink href="/services">All treatments</ArrowLink>
            </div>

            <Stagger className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-line bg-line md:grid-cols-3">
              {related.map((r) => (
                <StaggerItem key={r.slug}>
                  <Link
                    href={servicePath(r)}
                    className="group flex h-full flex-col bg-surface p-7 transition-colors duration-500 hover:bg-tint"
                  >
                    <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-sunk text-terracotta transition-colors group-hover:bg-white">
                      <ServiceIcon name={r.icon} className="h-5 w-5" />
                    </span>
                    <h3 className="mt-5 font-display text-xl leading-tight text-cocoa">
                      {r.name}
                    </h3>
                    <p className="mt-2.5 flex-1 text-sm leading-relaxed text-muted">
                      {r.summary}
                    </p>
                    <span className="mt-5 text-sm font-semibold text-brick">
                      Learn more →
                    </span>
                  </Link>
                </StaggerItem>
              ))}
            </Stagger>
          </div>
        </section>
      )}

      <CTABand
        eyebrow={service.name}
        title={["Book your", `${service.name.toLowerCase()} consultation.`]}
        body={`${service.name} consultations are available at our Civil Lines clinic in Prayagraj. Call or WhatsApp to book, ask a question or get directions.`}
        waText={`Hi, I'd like to ask about ${service.name} at Eclectic Dental Care.`}
      />
    </>
  );
}
